# Vanilla configuration
# Start with a minimal configuration that you can customize to build your code
# http://superblocks.com/docs/configuration/configuration-introduction/#section=configuration

version: 1
jobs:
  push_to_docker_registry_dev:
    image: docker:18.09.7
    services:
      - docker:18.09.7-dind
    script:
      - echo "$GITHUB_REGISTRY_TOKEN" | docker login docker.pkg.github.com --username $GITHUB_REGISTRY_USER --password-stdin
      - docker build --build-arg BUILD=build -t $GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1.dev .
      - docker push $GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1.dev

  deploy_to_dev:
    image: alpine
    script:
      - apk add --no-cache curl
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - kubectl config set-cluster $K8S_CLUSTER_NAME --server=$K8S_SERVER --insecure-skip-tls-verify=true
      - kubectl config set clusters.k8s.certificate-authority-data $K8S_CERTIFICATE_AUTHORITY_DATA
      - kubectl config set-credentials $K8S_USER_NAME --token=$K8S_USER_TOKEN
      - kubectl config set-context $K8S_CLUSTER_NAME --cluster=$K8S_CLUSTER_NAME --user=$K8S_USER_NAME
      - kubectl config use-context $K8S_CLUSTER_NAME
      - 'printf "apiVersion: v1\nkind: Secret\n$(kubectl create secret docker-registry $CI_PROJECT_NAME-github-registry --docker-server=$CI_REGISTRY --docker-username=$GITHUB_REGISTRY_USER --docker-password=$GITHUB_REGISTRY_TOKEN -o yaml --dry-run)" | kubectl apply -f -'
      - sed 's _APP_NAME_ '"$CI_PROJECT_NAME"' g; s _CONTAINER_IMAGE_ '"$GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1.dev"' g' kubernetes.tpl.yml > kubernetes.yml;
      - kubectl apply -f kubernetes.yml

  push_to_docker_registry_prod:
    image: docker:18.09.7
    services:
      - docker:18.09.7-dind
    script:
      - echo "$GITHUB_REGISTRY_TOKEN" | docker login docker.pkg.github.com --username $GITHUB_REGISTRY_USER --password-stdin
      - docker build --build-arg BUILD=build -t $GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1 .
      - docker push $GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1

  deploy_to_prod:
    image: alpine
    script:
      - apk add --no-cache curl
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - kubectl config set-cluster $K8S_CLUSTER_NAME_PROD --server=$K8S_SERVER_PROD --insecure-skip-tls-verify=true
      - kubectl config set clusters.k8s.certificate-authority-data $K8S_CERTIFICATE_AUTHORITY_DATA_PROD
      - kubectl config set-credentials $K8S_USER_NAME_PROD --token=$K8S_USER_TOKEN_PROD
      - kubectl config set-context $K8S_CLUSTER_NAME_PROD --cluster=$K8S_CLUSTER_NAME_PROD --user=$K8S_USER_NAME_PROD
      - kubectl config use-context $K8S_CLUSTER_NAME_PROD
      - 'printf "apiVersion: v1\nkind: Secret\n$(kubectl create secret docker-registry $CI_PROJECT_NAME-github-registry --docker-server=$CI_REGISTRY --docker-username=$GITHUB_REGISTRY_USER --docker-password=$GITHUB_REGISTRY_TOKEN -o yaml --dry-run)" | kubectl apply -f -'
      - sed 's _APP_NAME_ '"$CI_PROJECT_NAME"' g; s _CONTAINER_IMAGE_ '"$GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1"' g' kubernetes.tpl.yml > kubernetes.yml;
      - kubectl apply -f kubernetes.yml

stages:
  - build_dev:
      jobs:
        - push_to_docker_registry_dev:
            filters:
              only:
                - master
  - deploy_dev:
      jobs:
        - deploy_to_dev:
            filters:
              only:
                - master
   - build_prod:
      jobs:
        - push_to_docker_registry_prod:
            when: manual
            filters:
              only:
                - master
  - deploy_prod:
      jobs:
        - deploy_to_prod:
            filters:
              only:
                - master
